#!/usr/bin/env node
import{execFileSync,spawnSync}from"node:child_process";import{existsSync,readFileSync}from"node:fs";import{resolve,dirname}from"node:path";import{fileURLToPath}from"node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");const pkg=JSON.parse(readFileSync(resolve(root,"package.json"),"utf8"));
const C={NODE:"SF-1001",NPM:"SF-1002",INSTALL:"SF-2001",BUILD:"SF-2002",PKGCHECK:"SF-2101",PKGUPDATE:"SF-2102",GIT:"SF-3001",DIRTY:"SF-3002",NETWORK:"SF-3003",UPDATE:"SF-3004",UNKNOWN:"SF-9000"};
const die=(code,msg)=>{console.error("\n["+code+"] "+msg+"\nRun: npm run sf -- doctor");process.exit(1)};const has=x=>spawnSync(x,["--version"],{stdio:"ignore",shell:process.platform==="win32"}).status===0;
const run=(x,a=[],stdio="inherit")=>execFileSync(x,a,{cwd:root,stdio,shell:process.platform==="win32"});
function doctor(){console.log("\nStudy Flow Doctor");console.log("Version:",pkg.version);console.log("OS:",process.platform,process.arch);console.log("Node:",process.version);console.log("npm:",has("npm")?"OK":"MISSING");console.log("Git:",has("git")?"OK":"MISSING");console.log("Dependencies:",existsSync(resolve(root,"node_modules"))?"installed":"not installed");if(Number(process.versions.node.split(".")[0])<20)die(C.NODE,"Node.js 20+ is required.");}
function packageStatus(){if(!has("npm"))die(C.NPM,"npm was not found.");try{const out=String(run("npm",["outdated","--json"],"pipe")).trim();if(!out||out==="{}"){console.log("Packages: up to date");return{}}const data=JSON.parse(out);console.log("Outdated packages:",Object.keys(data).join(", "));return data}catch(e){if(e?.stdout){try{const data=JSON.parse(String(e.stdout)||"{}");console.log("Outdated packages:",Object.keys(data).join(", ")||"none");return data}catch{}}console.warn("["+C.PKGCHECK+"] Package update check unavailable.");return{}}}
function updatePackages(){const old=packageStatus();if(!Object.keys(old).length)return;try{console.log("Applying compatible package updates...");run("npm",["update"]);run("npm",["run","build"]);console.log("Compatible package updates complete. Major updates remain pinned for safety.")}catch{die(C.PKGUPDATE,"Package update/build failed. Review npm output.")}}
function setup(){doctor();if(!has("npm"))die(C.NPM,"npm was not found.");try{run("npm",["install"]);updatePackages();run("npm",["run","build"]);console.log("\nStudy Flow is ready. Run: npm run sf -- start")}catch{die(C.INSTALL,"Setup failed. Check the command output above.")}}
function update(checkOnly=false){if(!has("git"))die(C.GIT,"Git is required for source updates.");try{const dirty=String(run("git",["status","--porcelain"],"pipe")).trim();if(dirty)die(C.DIRTY,"Local changes detected. Commit or stash them before updating.");run("git",["fetch","origin","main"]);const local=String(run("git",["rev-parse","HEAD"],"pipe")).trim(),remote=String(run("git",["rev-parse","origin/main"],"pipe")).trim();if(local===remote){console.log("Study Flow is up to date.");return}console.log("Update available:",local.slice(0,7),"->",remote.slice(0,7));if(checkOnly)return;run("git",["pull","--ff-only","origin","main"]);run("npm",["install"]);updatePackages();run("npm",["run","build"]);console.log("Update complete.")}catch(e){if(e?.status===1)throw e;die(C.UPDATE,"Update failed. Check network, Git access and repository state.")}}
function start(){try{update(true)}catch{console.warn("[SF-3003] Update check skipped; continuing offline.")}try{run("npm",["run","dev","--","--host","127.0.0.1"])}catch{die(C.UNKNOWN,"Study Flow stopped unexpectedly.")}}
const cmd=process.argv[2]||"help";if(cmd==="setup")setup();else if(cmd==="start")start();else if(cmd==="doctor")doctor();else if(cmd==="update")update(false);else if(cmd==="check-update")update(true);else if(cmd==="packages")packageStatus();else if(cmd==="update-packages")updatePackages();else if(cmd==="version")console.log(pkg.version);else console.log("Study Flow CLI\n  setup | start | doctor | check-update | update | packages | update-packages | version");