import {useEffect,useState} from "react";import {AnimatePresence,motion} from "framer-motion";import {ArrowLeft,ArrowRight,BookOpen,Check,Download,ExternalLink,History,RotateCcw,Search,Sparkles} from "lucide-react";import {buildPlan,safeParse,type Plan} from "./engine";
const KEY="study-flow-state-v1",HISTORY="study-flow-history-v1";
export default function App(){const[step,setStep]=useState(1),[topic,setTopic]=useState(""),[description,setDescription]=useState(""),[count,setCount]=useState(5),[plan,setPlan]=useState<Plan|null>(null),[done,setDone]=useState<string[]>([]),[active,setActive]=useState<string|null>(null),[history,setHistory]=useState<Plan[]>([]);
useEffect(()=>{const saved=safeParse<{plan:Plan|null;done:string[]}>(localStorage.getItem(KEY),{plan:null,done:[]});setPlan(saved.plan);setDone(saved.done);setHistory(safeParse<Plan[]>(localStorage.getItem(HISTORY),[]));if(saved.plan)setStep(3)},[]);
useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({plan,done}))},[plan,done]);
function generate(){const next=buildPlan(topic,description,count);setPlan(next);setDone([]);setActive(null);const h=[next,...history.filter(x=>x.id!==next.id)].slice(0,20);setHistory(h);localStorage.setItem(HISTORY,JSON.stringify(h));setStep(3)}
function reset(){setStep(1);setTopic("");setDescription("");setPlan(null);setDone([]);setActive(null);localStorage.removeItem(KEY)}
function toggle(id:string){setDone(d=>d.includes(id)?d.filter(x=>x!==id):[...d,id])}
function exportPlan(){if(!plan)return;const blob=new Blob([JSON.stringify({plan,completed:done},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="study-flow-"+plan.topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")+".json";a.click();URL.revokeObjectURL(a.href)}
const lesson=plan?.lessons.find(x=>x.id===active);
return <main><div className="ambient a1"/><div className="ambient a2"/><header><div className="brand"><span><BookOpen size={20}/></span>Study Flow</div><nav><button className="navBtn" onClick={()=>setStep(4)}><History size={16}/> History</button></nav></header><section className="shell"><div className="statusbar"><span className="liveDot"/>LOCAL-FIRST <span>v1.0.0</span><span>SECURE STORAGE</span><span>AUTO-UPDATE READY</span></div><div className="progress"><i style={{width:(Math.min(step,3)/3*100)+"%"}}/></div>
<AnimatePresence mode="wait">{step===1&&<motion.div key="start" className="panel" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.32}}><p className="eyebrow">01 · START</p><h1>What do you want<br/>to <em>learn?</em></h1><p className="lead">Enter a topic and an optional goal. Your plan stays in this browser.</p><label>TOPIC<input maxLength={100} autoFocus value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Network Security"/></label><label>DESCRIPTION <span>OPTIONAL</span><textarea maxLength={500} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Your goal, level, or areas to focus on"/></label><button disabled={!topic.trim()} onClick={()=>setStep(2)}>Continue <ArrowRight size={18}/></button></motion.div>}
{step===2&&<motion.div key="structure" className="panel" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.32}}><p className="eyebrow">02 · STRUCTURE</p><h1>Choose your<br/><em>depth.</em></h1><p className="lead">Choose between one and ten learning stages for <b>{topic}</b>.</p><div className="count"><strong>{count}</strong><span>STAGES</span></div><input className="range" type="range" min="1" max="10" value={count} onChange={e=>setCount(Number(e.target.value))}/><div className="rangeLabels"><span>1 · FOCUSED</span><span>10 · DEEP</span></div><div className="actions"><button className="ghost" onClick={()=>setStep(1)}><ArrowLeft size={18}/> Back</button><button onClick={generate}><Sparkles size={18}/> Build flow</button></div></motion.div>}
{step===3&&plan&&!lesson&&<motion.div key="flow" className="panel wide" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.32}}><p className="eyebrow">03 · LEARNING FLOW</p><h1>{plan.topic}</h1>{plan.description&&<p className="lead">{plan.description}</p>}<div className="meter"><i style={{width:(done.length/plan.lessons.length*100)+"%"}}/></div><div className="cards">{plan.lessons.map((l,i)=><div className={"card "+(done.includes(l.id)?"complete":"")} key={l.id}><button className="cardOpen" onClick={()=>setActive(l.id)}><span>{String(i+1).padStart(2,"0")}</span><b>{l.title}</b><ArrowRight size={18}/></button><button className="tick" aria-label="Toggle complete" onClick={()=>toggle(l.id)}>{done.includes(l.id)?<Check size={17}/>:null}</button></div>)}</div><div className="footer"><span>{done.length}/{plan.lessons.length} completed</span><div className="row"><button className="ghost" onClick={exportPlan}><Download size={16}/> Export</button><button className="ghost" onClick={reset}><RotateCcw size={16}/> New</button></div></div></motion.div>}
{step===3&&lesson&&<motion.div key={"lesson-"+lesson.id} className="panel wide lesson" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}}><button className="backlink" onClick={()=>setActive(null)}><ArrowLeft size={16}/> Learning flow</button><p className="eyebrow">LESSON {lesson.id}</p><h1>{lesson.title}</h1><p className="lead">{lesson.summary}</p><h3>Learning objectives</h3><ul>{lesson.objectives.map(x=><li key={x}>{x}</li>)}</ul><h3>Practice</h3><div className="practice">{lesson.practice}</div><div className="actions"><a className="search" target="_blank" rel="noreferrer" href={"https://www.google.com/search?q="+encodeURIComponent(lesson.searchQuery)}><Search size={17}/> Research topic <ExternalLink size={14}/></a><button onClick={()=>{toggle(lesson.id);setActive(null)}}><Check size={17}/> {done.includes(lesson.id)?"Mark incomplete":"Complete lesson"}</button></div></motion.div>}
{step===4&&<motion.div key="history" className="panel wide" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0}}><button className="backlink" onClick={()=>setStep(plan?3:1)}><ArrowLeft size={16}/> Back</button><p className="eyebrow">HISTORY</p><h1>Your learning<br/><em>library.</em></h1>{history.length===0?<p className="lead">No saved flows yet.</p>:<div className="cards">{history.map(p=><button className="historyCard" key={p.id} onClick={()=>{setPlan(p);setDone([]);setActive(null);setStep(3)}}><div><b>{p.topic}</b><span>{p.lessons.length} stages · {new Date(p.createdAt).toLocaleDateString()}</span></div><ArrowRight size={18}/></button>)}</div>}</motion.div>}</AnimatePresence>\n</section></main>}