import {useEffect,useMemo,useState} from "react";import {ArrowLeft,ArrowRight,BookOpen,Check,RotateCcw,Sparkles} from "lucide-react";
type Plan={topic:string;description:string;count:number;branches:string[]};
const suggestions=["Foundations","Core concepts","Key terminology","Practical skills","Common patterns","Tools & workflow","Applied examples","Advanced concepts","Practice","Review & next steps"];
export default function App(){const[step,setStep]=useState(1);const[topic,setTopic]=useState("");const[description,setDescription]=useState("");const[count,setCount]=useState(5);const[plan,setPlan]=useState<Plan|null>(null);const[done,setDone]=useState<number[]>([]);
useEffect(()=>{try{const raw=localStorage.getItem("study-flow-plan");if(raw)setPlan(JSON.parse(raw))}catch{}},[]);
const branches=useMemo(()=>suggestions.slice(0,count).map((x,i)=>i===0?(topic||"Topic")+" — "+x:x),[count,topic]);
function generate(){const next={topic:topic.trim(),description:description.trim(),count,branches};setPlan(next);setDone([]);localStorage.setItem("study-flow-plan",JSON.stringify(next));setStep(3)}
function reset(){setStep(1);setTopic("");setDescription("");setPlan(null);setDone([]);localStorage.removeItem("study-flow-plan")}
return <main><header><div className="brand"><span><BookOpen size={20}/></span>Study Flow</div><div className="tag">LOCAL LEARNING PLANNER</div></header><section className="shell"><div className="progress"><i style={{width:(step/3*100)+"%"}}/></div>
{step===1&&<div className="panel"><p className="eyebrow">01 · START</p><h1>What do you want<br/>to <em>learn?</em></h1><p className="lead">Give Study Flow a topic. Add context if you want a more focused learning path.</p><label>TOPIC <input autoFocus value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Network Security"/></label><label>DESCRIPTION <span>OPTIONAL</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What do you want to understand or achieve?"/></label><button disabled={!topic.trim()} onClick={()=>setStep(2)}>Continue <ArrowRight size={18}/></button></div>}
{step===2&&<div className="panel"><p className="eyebrow">02 · STRUCTURE</p><h1>Choose your<br/><em>depth.</em></h1><p className="lead">How many focused branches should <b>{topic}</b> be divided into?</p><div className="count"><strong>{count}</strong><span>SUBTOPICS</span></div><input className="range" type="range" min="1" max="10" value={count} onChange={e=>setCount(Number(e.target.value))}/><div className="rangeLabels"><span>1 · FOCUSED</span><span>10 · DEEP</span></div><div className="actions"><button className="ghost" onClick={()=>setStep(1)}><ArrowLeft size={18}/> Back</button><button onClick={generate}><Sparkles size={18}/> Build flow</button></div></div>}
{step===3&&plan&&<div className="panel wide"><p className="eyebrow">03 · YOUR FLOW</p><h1>{plan.topic}</h1>{plan.description&&<p className="lead">{plan.description}</p>}<div className="cards">{plan.branches.map((b,i)=><button className={"card "+(done.includes(i)?"complete":"")} key={b} onClick={()=>setDone(d=>d.includes(i)?d.filter(x=>x!==i):[...d,i])}><span>{String(i+1).padStart(2,"0")}</span><b>{b}</b><i>{done.includes(i)?<Check size={18}/>:<ArrowRight size={18}/>}</i></button>)}</div><div className="footer"><span>{done.length}/{plan.count} completed</span><button className="ghost" onClick={reset}><RotateCcw size={16}/> New topic</button></div></div>}
</section></main>}