export type Lesson={id:string;title:string;summary:string;notes:string;objectives:string[];practice:string;searchQuery:string};
export type Plan={id:string;topic:string;description:string;createdAt:string;lessons:Lesson[]};
export type AIProvider="openai"|"groq"|"openrouter"|"ollama"|"custom";
export type AISettings={provider:AIProvider;endpoint:string;apiKey:string;model:string;customModel:boolean};
export const PROVIDERS:Record<AIProvider,{label:string;endpoint:string;model:string;keyRequired:boolean}>={openai:{label:"OpenAI",endpoint:"https://api.openai.com/v1",model:"gpt-4o-mini",keyRequired:true},groq:{label:"Groq Cloud",endpoint:"https://api.groq.com/openai/v1",model:"llama-3.3-70b-versatile",keyRequired:true},openrouter:{label:"OpenRouter Cloud",endpoint:"https://openrouter.ai/api/v1",model:"openai/gpt-4o-mini",keyRequired:true},ollama:{label:"Ollama Cloud",endpoint:"https://ollama.com/v1",model:"gpt-oss:20b-cloud",keyRequired:true},custom:{label:"Custom AI Provider",endpoint:"",model:"",keyRequired:false}};
export function normalizeAI(raw:Partial<AISettings>|null|undefined):AISettings{const provider:AIProvider=raw?.provider&&raw.provider in PROVIDERS?raw.provider:"openai";return{provider,endpoint:typeof raw?.endpoint==="string"?raw.endpoint:"",apiKey:typeof raw?.apiKey==="string"?raw.apiKey:"",model:typeof raw?.model==="string"?raw.model:"",customModel:typeof raw?.customModel==="boolean"?raw.customModel:false}}
export function resolvedAI(input:AISettings){const s=normalizeAI(input);const p=PROVIDERS[s.provider];return{...s,endpoint:s.provider==="custom"?s.endpoint:p.endpoint,model:s.customModel||s.provider==="custom"?s.model:p.model}}
type AIPlan={subtopics:Array<{title:string;summary:string;objectives:string[];practice:string;searchQuery?:string}>};
function cleanEndpoint(v:string){return v.trim().replace(/\/$/,"")}
function extractJSON(text:string){const fenced=text.match(/```(?:json)?\s*([\s\S]*?)```/i);const raw=(fenced?.[1]||text).trim();const a=raw.indexOf("{"),b=raw.lastIndexOf("}");if(a<0||b<a)throw new Error("AI response did not contain valid JSON.");return JSON.parse(raw.slice(a,b+1))}
export async function buildPlanAI(topic:string,description:string,count:number,s:AISettings):Promise<Plan>{
 const clean=topic.trim();if(!clean)throw new Error("Topic is required.");s=resolvedAI(s);if(!s.endpoint.trim()||!s.model.trim())throw new Error("Configure AI provider and model in Settings.");
 const prompt=`Create a learning tree for the MAIN TOPIC: "${clean}". Topic details: "${description.trim()||"Not provided"}". Generate exactly ${count} distinct subtopics. The root/main topic must NOT be repeated as a subtopic. Return ONLY JSON with this schema: {"subtopics":[{"title":"...","summary":"...","notes":"...","objectives":["...","...","..."],"practice":"...","searchQuery":"..."}]}. Make subtopics specific to the topic and logically ordered. Write every summary, notes section, objective and practice task for a complete beginner. The notes must be a clear detailed explanation using simple language, defining unfamiliar terms and giving at least one concrete example. Avoid unexplained jargon.`;
 const headers:Record<string,string>={"Content-Type":"application/json"};if(s.apiKey.trim())headers.Authorization="Bearer "+s.apiKey.trim();
 const res=await fetch(cleanEndpoint(s.endpoint)+"/chat/completions",{method:"POST",headers,body:JSON.stringify({model:s.model.trim(),messages:[{role:"system",content:"You are Study Flow, a curriculum planning assistant. Follow the requested JSON schema exactly."},{role:"user",content:prompt}],temperature:.35})});
 if(!res.ok){let detail="";try{detail=(await res.text()).slice(0,240)}catch{}throw new Error("AI request failed ("+res.status+"). "+detail)}
 const data=await res.json();const text=data?.choices?.[0]?.message?.content;if(typeof text!=="string")throw new Error("AI provider returned an unsupported response.");
 const parsed=extractJSON(text) as AIPlan;if(!Array.isArray(parsed.subtopics)||parsed.subtopics.length<count)throw new Error("AI returned fewer subtopics than requested.");
 const lessons=parsed.subtopics.slice(0,count).map((x,i)=>({id:String(i+1),title:String(x.title||("Subtopic "+(i+1))).trim(),summary:String(x.summary||"").trim(),notes:String((x as any).notes||x.summary||"").trim(),objectives:Array.isArray(x.objectives)?x.objectives.slice(0,5).map(String):[],practice:String(x.practice||"").trim(),searchQuery:String(x.searchQuery||clean+" "+x.title).trim()}));
 return{id:Date.now().toString(36),topic:clean,description:description.trim(),createdAt:new Date().toISOString(),lessons}
}
export async function testAI(s:AISettings){s=resolvedAI(s);if(!s.endpoint.trim()||!s.model.trim())throw new Error("Endpoint and model are required.");const headers:Record<string,string>={"Content-Type":"application/json"};if(s.apiKey.trim())headers.Authorization="Bearer "+s.apiKey.trim();const res=await fetch(cleanEndpoint(s.endpoint)+"/chat/completions",{method:"POST",headers,body:JSON.stringify({model:s.model.trim(),messages:[{role:"user",content:"Reply with OK only."}],max_tokens:8})});if(!res.ok)throw new Error("Connection failed ("+res.status+").");return true}
export function safeParse<T>(raw:string|null,fallback:T):T{if(!raw)return fallback;try{return JSON.parse(raw) as T}catch{return fallback}}
